export const TOUR_DATE_CREATE_REQUEST = 'TOUR_DATE_CREATE_REQUEST'
export const TOUR_DATE_CREATE_SUCCESS = 'TOUR_DATE_CREATE_SUCCESS'
export const TOUR_DATE_CREATE_FAIL = 'TOUR_DATE_CREATE_FAIL'
export const TOUR_DATE_CREATE_RESET = 'TOUR_DATE_CREATE_RESET'

export const TOUR_DATES_REQUEST = 'TOUR_DATES_REQUEST'
export const TOUR_DATES_SUCCESS = 'TOUR_DATES_SUCCESS'
export const TOUR_DATES_FAIL = 'TOUR_DATES_FAIL'

export const TOUR_DATE_REQUEST = 'TOUR_DATE_REQUEST'
export const TOUR_DATE_SUCCESS = 'TOUR_DATE_SUCCESS'
export const TOUR_DATE_FAIL = 'TOUR_DATE_FAIL'

export const TOUR_DATE_DELETE_REQUEST = 'TOUR_DATE_DELETE_REQUEST'
export const TOUR_DATE_DELETE_SUCCESS = 'TOUR_DATE_DELETE_SUCCESS'
export const TOUR_DATE_DELETE_FAIL = 'TOUR_DATE_DELETE_FAIL'

export const TOUR_DATE_UPDATE_REQUEST = 'TOUR_DATE_UPDATE_REQUEST'
export const TOUR_DATE_UPDATE_SUCCESS = 'TOUR_DATE_UPDATE_SUCCESS'
export const TOUR_DATE_UPDATE_FAIL = 'TOUR_DATE_UPDATE_FAIL'
